name: tauri-ci
on:
  workflow_call:

# Explanation
# - ${{ github.workflow }}: the workflow name is used to generate the concurrency
# group (e.g. Workflow 1). That allows you to have more than one different workflow
# (eg. workflow1.yaml and workflow2.yaml) triggered on the same event (e.g. a PR).
# Otherwise, workflow1.yaml would cancel workflow2.yaml or viceversa.
# - ${{ github.event.pull_request.number: when the trigger event is a PR, it will
# use the PR number to generate the concurrency group (e.g. workflow1-33).
# - || github.ref }}: when the trigger is not a PR but a push, it will use the branch
# or tag name to generate the concurrency group (e.g. workflow1-branch1).
# - cancel-in-progress: true: if cancel-in-progress is omitted or set to false, when
# a new workflow is triggered, the currently running workflow won't be cancelled, and
# the new workflow will be queued pending until the previous one is done.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2
        with:
            version: 8
      - name: Install frontend dependencies
        run: pnpm install --production
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build app
        run: pnpm tauri build
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
            name: ${{ matrix.platform }}
            path: |
              src-tauri/target/release/bundle/dmg/*.dmg
              src-tauri/target/release/bundle/appimage/*.AppImage
              src-tauri/target/release/bundle/deb/*.deb
              src-tauri/target/release/bundle/msi/*.msi
              src-tauri/target/release/bundle/nsis/*.exe
            retention-days: 3
